{% set name = "pylodstorage" %}
{% set version = "0.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pylodstorage-{{ version }}.tar.gz
  sha256: F77ABBE4AAA3DA25AF384A9A8115194262C82335D22504C6A94D9EF18FC55020

build:
  entry_points:
    - sparqlquery = lodstorage.querymain:mainSPARQL
    - sqlquery=lodstorage.querymain:mainSQL
    - lodquery=lodstorage.querymain:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - dicttoxml2
    - jsonpickle
    - matplotlib-base
    - numpy
    - pandas
    - pygments
    - pylatexenc >=2.10
    - python >={{ python_min }}
    - pyyaml
    - sparqlwrapper
    - tabulate

test:
  imports:
    - lodstorage
    - sampledata
  commands:
    - pip check
    - sparqlquery --help
    - sqlquery --help
    - lodquery --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/WolfgangFahl/pyLodStorage
  summary: python List of Dict (Table) Storage library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cml37
